### ISSUE TITLE
Name is not appearing properly.

### ISSUE THREAD

**Issue by ghost** [FishPhd/DewritoLauncher#10]
Though my name is set as "SwarM" in the launcher, it doesn't appear as faggot. Please fix ASAP.

**Comment by FishPhd** [comment]
Im so sorry to hear this unfortunately It doesn't check for capital letters i will change this

**Comment by SteelSliver** [comment]
this is game breaking Fish hurry

**Comment by FishPhd** [comment]
This has been fixed. Thank you for your patience.
