### ISSUE TITLE
XamlParseException on build of most recent

### ISSUE THREAD

**Issue by scooterpsu** [FishPhd/DewritoLauncher#3]
I'm having the same problem I was when FishPhd posted a test build on IRC, where it crashes without opening.

Debugging with Visual Studio gave me this error.

http://pastebin.com/BMGbV68e

**Comment by scooterpsu** [comment]
Ignore me, I'm dumb.

**Comment by Pflughaupt** [comment]
I'm having a very similar problem except with PresentationFramework.dll, specifically  PresentationFramework.Default Style (that I can't find mention of anywhere) according to InnerException. How did you resolve your issue?
