### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by jshearer12** [FishPhd/DewritoLauncher#31]
Whenever I try to play the game after I have updated I get an error saying, "The program can't start because d3dx9_43.dll is missing from your computer try reinstalling to fix this problem."

**Comment by FishPhd** [comment]
Install everything in tpi folder in halo online.

**Comment by jshearer12** [comment]
Install what to tpi? I tried installing the Eldewrito-Installer into tpi and I got the same error. I have literally been trying for hours to get this game and nothing is working.

-------- Original message --------

**Comment by FishPhd** [comment]
Install every exe in the tpi folder DONT place the updater in it. This isn't even an updater issue you just somehow haven't managed to install directx correctly.

**Comment by jshearer12** [comment]
What do you mean by every exe? What do I put in tpi? I'm sorry I don't understand.

-------- Original message --------

**Comment by FishPhd** [comment]
Step 1: Open windows explorer
Step 2: Open halo online folder
Step 3: Open tpi folder
Step 4: Click on every exe and install it
Step 5: Follow tutorial for installing halo online like normal

Once again this is not an updater issue just google the error if you have other problems

**Comment by jshearer12** [comment]
I'm sorry for acting so stupid. Thanks for the help. I got it working now.
