### ISSUE TITLE
launcher not launching windows 10

### ISSUE THREAD

**Issue by xXTHEBIGZXx** [FishPhd/DewritoLauncher#40]
(i know this apears in already closed issues but non of them helped) upon opening the launcher it crashed instantly but created the proper files alsoo it seames to open twice as there are 2 "this windows has stoped working" notifications every time i try to open it i have tryed different compatabilitys, running with admin, editing the prefs and configs (wich probly what broke my server browser) i have installed everything in the tpi folder im running windows 10 64bit, im not sure my system specs will help but here they are anyway AMD FX 6350, 8gb ram, gtx 750 ti sc thats all i can get sorry if there isnt enough here to fix anything

**Comment by FishPhd** [comment]
Install .net 4.5.2
