### ISSUE TITLE
 dewritwo has stopped working - help 

### ISSUE THREAD

**Issue by Rammsey** [FishPhd/DewritoLauncher#41]
Hi all I have a problem with the halo online I need of help for solve

when I opened the launcher DewritoUpdater.exe appears:

dewritwo has stopped working

![errorr](https://cloud.githubusercontent.com/assets/17414447/13231498/25c27690-d978-11e5-865b-7d10f57d07cb.jpg)

it installed the drives and DirectX 

help please 

maybe you look a little weird my post is because I speak Spanish and not English

**Comment by twist84** [comment]
Do you have .Net 4.5.2 installed?

**Comment by Rammsey** [comment]
TheTwist84 That's I need thanks :D
