### ISSUE TITLE
Strange problem when updating to 5.1.1

### ISSUE THREAD

**Issue by Lear62** [FishPhd/DewritoLauncher#44]
When i run the launcher it gives me a verification screen for about 10 seconds then promps me to update, after clicking the update button the launcher instantly crashes (DewritoUpdater.exe has stopped working) and for some reason renames itself to DewritoUpdater.exe.old in the files, tried to re-download launcher a couple of times but still no change. Anyone have a clue how to fix this?

**Comment by NoShotz** [comment]
We know, read top comment on the 5.2 thread

**Comment by NoShotz** [comment]
5.1*

**Comment by FishPhd** [comment]
https://github.com/ElDewrito/DewritoUpdater
