### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by elizabwth** [FishPhd/DewritoLauncher#6]
When attempting to open the new launcher I get "DoritoPatcherWPF has stopped working." I tried this with both my old installation and a clean installation of Halo Online.

I'm running Windows 7.

Here's what the crash window spits out, though I'm not sure helpful it will be.

```
Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: DewritoUpdater.exe
  Problem Signature 02: 1.0.0.0
  Problem Signature 03: 556622e2
  Problem Signature 04: System.Core
  Problem Signature 05: 4.0.30319.34209
  Problem Signature 06: 53489a70
  Problem Signature 07: 43e
  Problem Signature 08: 4d
  Problem Signature 09: System.Windows.Markup.XamlParse
  OS Version:   6.1.7601.2.1.0.256.1
```

Screenshot:
![](http://puu.sh/i3s6U/0ca18ea877.png)

Let me know if you need any more information.

**Comment by Jordach** [comment]
Disable custom windows themes, this is the cause of the crashes.

**Comment by Gaaraale** [comment]
areglenlo me please and lansador not work in windows 7

**Comment by elizabwth** [comment]
Disabling my theme worked, thank you.

**Comment by UPLYNXED** [comment]
To those of you who had issues with custom themes and the launcher, please run the crash test version and upload the results on pastebin, thanks.
http://armorwatcher.com/files/ElDewritoLauncherCrashDebug.zip

**Comment by elizabwth** [comment]
Here you are.
http://pastebin.com/dNA77MSj

I'm using the theme [Elune](http://minhtrimatrix.deviantart.com/art/Elune-199350232).

**Comment by UPLYNXED** [comment]
Please try running this version:
http://armorwatcher.com/files/ElDewritoLauncherCrashDebug3.zip

**Comment by elizabwth** [comment]
http://pastebin.com/HU8jZxKs

**Comment by Tempystral** [comment]
Debug3 works when I launch it with one of the default themes. When launching it with Valley, I get http://pastebin.com/QQFDPrBf

**Comment by UPLYNXED** [comment]
We have put this issue on the backburner for now, sorry.

**Comment by mccapital** [comment]
Hey i just downloaded the game and copied all the folders i need into halo, then i ran the launcher and it verifies everything, then when i click update the program says dewritolauncher stopped working? anyone know a fix
