### ISSUE TITLE
Crash on startup (Windows 8.1)

### ISSUE THREAD

**Issue by Tempystral** [FishPhd/DewritoLauncher#8]
This error is much like the one Elizabwth had:

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: DewritoUpdater.exe
  Problem Signature 02: 1.0.0.0
  Problem Signature 03: 556622e2
  Problem Signature 04: System.Core
  Problem Signature 05: 4.0.30319.34209
  Problem Signature 06: 53489a70
  Problem Signature 07: 43e
  Problem Signature 08: 4d
  Problem Signature 09: System.Windows.Markup.XamlParse
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    1033
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: dba6
  Additional Information 4: dba6f3f51243e7af8337f6bced10f1a2

However, I've done some research and it would seem that the fix for Windows 7 won't work on Windows 8.1 as a result of the fact that the Desktop Windows Manager can't be turned off, as it can in 7. I don't have the compatibility option to disable custom themes, and as such, I'm stuck without a working launcher.

Any help or insight is appreciated.

**Comment by UPLYNXED** [comment]
To those of you who had issues with custom themes and the launcher, please run the crash test version and upload the results on pastebin, thanks.
http://armorwatcher.com/files/ElDewritoLauncherCrashDebug.zip

**Comment by Tempystral** [comment]
Thanks for trying to figure this out. I quite like my custom theme.

http://pastebin.com/VS197pvR

**Comment by UPLYNXED** [comment]
~~Can you test this version? 
http://armorwatcher.com/files/ElDewritoLauncherCrashDebug2.zip~~

Can you try using another theme? In particular one that is not Summit or Valley?

**Comment by UPLYNXED** [comment]
You're having the exact same issue as this issue: https://github.com/FishPhd/DewritoLauncher/issues/6
Please continue discussion there, thanks :)
